@baseURL = http://localhost:8080/todos

###
# Get all todos
GET {{baseURL}}


###
# Create todo
POST {{baseURL}}
Content-Type: application/json

{
    "title": "Learn Go",
    "description": "I want to learn and master Go",
    "completed": false
}


###
# Get all todos
GET {{baseURL}}


###
# Create without title
POST http://localhost:8080/todos
Content-Type: application/json

{
    "description": "This todo only has description."
}


###
# Create without description
POST {{baseURL}}
Content-Type: application/json

{
    "title": "This todo only has title"
}


###
# Create without any fields
POST {{baseURL}}
Content-Type: application/json

{
}


###
# Create with invalid fileds
POST {{baseURL}}
Content-Type: application/json

{
    "id": 34
}


### Create with invalid fileds and title
POST {{baseURL}}
Content-Type: application/json

{
    "abc": 34,
    "title": "This todo has an invalid field.",
    "done": true
}


###
# Get all todos
GET {{baseURL}}

