@baseURL = http://localhost:8080/todos

###
# Get all todos
GET {{baseURL}}


###
# Delete id 0
DELETE {{baseURL}}/0


###
# Get all todos
GET {{baseURL}}


###
# Delete id -1
DELETE {{baseURL}}/-1


###
# Get all todos
GET {{baseURL}}


### Delete id 's'
DELETE {{baseURL}}/s


###
# Get all todos
GET {{baseURL}}
